# Generated by Django 2.2.7 on 2019-11-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='novel_category',
            field=models.CharField(default='tyouhen', max_length=5),
        ),
        migrations.AddField(
            model_name='novel',
            name='novel_status',
            field=models.CharField(default='rensaichuu', max_length=5),
        ),
    ]
